C:\Lazarus\fpc\2.2.4\bin\i386-win32\delp "C:\Spiele\Lazarus_Projects\Technobase fm Player\TechnoBaseFM Player - Lazarus"
del *.res
del *.or
del *.o
del *.ppu
del *.dfm
del *.a
del *.ddp
del *.drc
del *.dof
del *.~pas
del *.dcu
del *.cfg
del *.~dpr
del *.mes
del *.map
del *.~ddp
del *.~dfm
del *.rst
del *.manifest
del *.compiled
del *.lrs
del *.rc
del *.exe
del *.dll
del /F /Q backup
rmdir /Q /S backup
@pause